version: '3.8'
services:
  api:
    image: golang:1.19
    container_name: bridge-golib
    volumes:
      - ./:/app/
    working_dir: /app/
    networks:
      - main
networks:
  main:
    name: bridge-gatekeeper
