name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CI_ENV: true
jobs:
  golib:
    name: golib
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    defaults:
      run:
        working-directory: src/golib
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run Tests
      run: make test
  gatekeeper:
    name: gatekeeper
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    defaults:
      run:
        working-directory: src/gatekeeper
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run Tests
      run: make test
